"""Update user model

Revision ID: 95e735cbeb17
Revises: 39fa790f8d4f
Create Date: 2024-07-16 23:13:53.326830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95e735cbeb17'
down_revision = '39fa790f8d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spread_data', postgresql.JSON(astext_type=sa.Text()), nullable=False))
        batch_op.drop_constraint('readings_spread_id_fkey', type_='foreignkey')
        batch_op.drop_column('spread_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_user_id', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['auth0_user_id'])
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_user_id')

    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spread_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('readings_spread_id_fkey', 'spreads', ['spread_id'], ['id'])
        batch_op.drop_column('spread_data')

    # ### end Alembic commands ###
