"""Remove extra column

Revision ID: e086ba9f75c5
Revises: b92f65e7911b
Create Date: 2024-07-12 13:17:07.090190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e086ba9f75c5'
down_revision = 'b92f65e7911b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('some_test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('some_test', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
