name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest autopep8 responses

      - name: Debug Environment Variables
        run: |
          echo "BASE_URL: $BASE_URL"
          echo "API_KEY: $API_KEY"

      - name: Run tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: pytest

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive --exclude=migrations,venv,__pycache__ .

      - name: Check for modified files (excluding __pycache__ and binary files)
        id: git-check
        run: |
          if [[ -n $(git status -s | grep -v "/__pycache__/" | grep -v "\.pyc$" | grep -v "^ M") ]]; then
            echo "modified=true" >> $GITHUB_ENV
            git diff
            exit 1
          fi

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git commit -am "Apply autopep8 formatting"
          git push
